core/urls.py
from django.urls import path
from core import views


app_name = 'core'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('create/', views.AccountCreateView.as_view(), name='create'),
    path('list/', views.AccountListView.as_view(), name='list'),
    path('<int:id>/update/', views.AccountUpdateView.as_view(), name='update'),
    path('<int:id>/delete/', views.AccountDeleteView.as_view(), name='delete'),
    path('<int:id>/set-main/', views.SetMainAccountView.as_view(), name='set_main'),
    path('update-balance/', views.UpdateBalanceView.as_view(), name='update_balance'),
    path('get-pairs/', views.GetPairsView.as_view(), name='get_pairs'),
    path('set-cross-margin/', views.SetCrossMarginView.as_view(), name='set_cross_margin'),
    path('set-leverage/', views.SetLeverageView.as_view(), name='set_leverage'),
]

dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
]

core/models.py
from django.db import models


class BaseModel(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Account(BaseModel):
    name = models.CharField(max_length=255, unique=True)
    secret_key = models.CharField(max_length=255, unique=True)
    api_key = models.CharField(max_length=255, unique=True)
    balance = models.DecimalField(default=0, decimal_places=2, max_digits=10)

    def __str__(self) -> str:
        return self.name


class Pair(BaseModel):
    account = models.ForeignKey(
        'core.Account', on_delete=models.CASCADE, related_name='pairs')
    name = models.CharField(max_length=55, unique=True)
    quantity_precision = models.IntegerField()

    class Meta:
        ordering = ['name']

    def __str__(self) -> str:
        return self.name

core/views.py
import copy
from decimal import Decimal

from django.shortcuts import render, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic.list import ListView
from django.views.generic.edit import DeleteView
from django.contrib import messages
from django.http import HttpResponseRedirect

from core.models import Account
from core.integrations.binance_futures.integration import Integration
from core.resources.serializers import AccountSerializer, OrderSerializer
from core.resources.service import OrderService, PairService
from core.tasks import get_pairs_task, update_balance_task, set_cross_margin_task, set_leverage_task


class IndexView(View):
    template_name = "core/index.html"
    pair_service = PairService()
    order_service = OrderService()

    def get_context_data(self, request, *args, **kwargs):
        account = self._get_selected_account(request.session)
        if account:
            context = {"selected_account": account}
        else:
            try:
                del request.session["selected_account_id"]
            except KeyError:
                pass
        return context

    def _get_selected_account(self, session):
        account_id = session.get("selected_account_id")
        try:
            account = Account.objects.prefetch_related(
                "pairs").get(id=account_id)
        except Account.DoesNotExist:
            account = None
        return account

    def get(self, request, *args, **kwargs):
        context_data = self.get_context_data(request, *args, **kwargs)
        return render(request, self.template_name, context=context_data)

    def post(self, request, *args, **kwargs):
        request_data = copy.deepcopy(request.POST)
        if "buy" in request_data:
            request_data.update({"side": "BUY"})
        else:
            request_data.update({"side": "SELL"})

        serializer = OrderSerializer(data=request_data)
        if not serializer.is_valid():
            for err in serializer.errors:
                messages.add_message(
                    request, messages.WARNING, str(serializer.errors[err]))
            return HttpResponseRedirect(reverse('core:index'))

        order_data = serializer.validated_data
        account = self._get_selected_account(request.session)
        integration = Integration(account)

        pair = self.pair_service.get_pair_object(
            order_data.get("pair"))
        pair_price = integration.run_command(
            "get_pair_price", pair=pair)

        quantity = self.order_service.calculate_quantity(
            balance=account.balance,
            multiplier=order_data.get("multiplier"),
            price=pair_price,
            precision=pair.quantity_precision)

        order_data.update(
            {"symbol": pair.name, "quantity": quantity})

        order_result = integration.run_command(
            "create_order", order_params=order_data)

        if order_result:
            pair = order_result.get("symbol")
            avg_price = order_result.get("avgPrice")
            quantity = order_result.get("executedQty")
            side = order_result.get("side")
            size = Decimal(avg_price) * Decimal(quantity)
            messages.add_message(request, messages.SUCCESS,
                                 f"{size} USDT {side} order executed on {pair}, entry price : {avg_price}")
        else:
            messages.add_message(request, messages.WARNING,
                                 "Unexpected error on order creation")
        return HttpResponseRedirect(reverse('core:index'))


class AccountCreateView(View):
    template_name = "core/create.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        request_data = request.POST
        serializer = AccountSerializer(data=request_data)
        if serializer.is_valid():
            try:
                serializer.create(serializer.validated_data)
                return HttpResponseRedirect(reverse('core:index'))
            except Exception as e:
                messages.add_message(request, messages.WARNING, str(e))
        else:
            for err in serializer.errors:
                messages.add_message(
                    request, messages.WARNING, str(serializer.errors[err]))

        return HttpResponseRedirect(reverse('core:create'))


class SetMainAccountView(View):
    def get_object(self, request, object_id):
        return Account.objects.filter(id=object_id)

    def get(self, request, *args, **kwargs):
        account_id = self.kwargs.get("id")
        if self.get_object(request, account_id).exists():
            request.session["selected_account_id"] = account_id
        return HttpResponseRedirect(reverse("core:index"))


class AccountListView(ListView):
    model = Account
    template_name = "core/list.html"


class AccountUpdateView(View):
    template_name = "core/update.html"
    model = Account

    def get(self, request, *args, **kwargs):
        obj = get_object_or_404(self.model, id=self.kwargs.get("id"))
        return render(request, self.template_name, {"account": obj})

    def post(self, request, *args, **kwargs):
        obj = get_object_or_404(self.model, id=self.kwargs.get("id"))
        request_data = request.POST
        serializer = AccountSerializer(data=request_data)
        if serializer.is_valid():
            try:
                serializer.update(obj, serializer.validated_data)
                return HttpResponseRedirect(reverse('core:list'))
            except Exception as e:
                messages.add_message(request, messages.WARNING, str(e))
        else:
            for err in serializer.errors:
                messages.add_message(
                    request, messages.WARNING, str(serializer.errors[err]))
                    
        return HttpResponseRedirect(reverse('core:update', kwargs={'id': obj.id}))


class AccountDeleteView(DeleteView):
    model = Account
    success_url = reverse_lazy('core:list')
    template_name = "core/delete.html"
    pk_url_kwarg = "id"
    context_object_name = "account"


class UpdateBalanceView(View):
    def get(self, request, *args, **kwargs):
        update_balance_task()
        return HttpResponseRedirect(reverse('core:index'))


class GetPairsView(View):
    def get(self, request, *args, **kwargs):
        get_pairs_task()
        return HttpResponseRedirect(reverse('core:index'))


class SetCrossMarginView(View):
    def get(self, request, *args, **kwargs):
        set_cross_margin_task()
        return HttpResponseRedirect(reverse('core:index'))


class SetLeverageView(View):
    def get(self, request, *args, **kwargs):
        set_leverage_task()
        return HttpResponseRedirect(reverse('core:index'))

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</head>
<body class="bg-dark">
    <nav class="navbar fixed-bottom navbar-expand-lg bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'core:index' %}">Dashboard</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if accounts %}
                    <li class="nav-item dropup">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Accounts</a>
                        <ul class="dropdown-menu">
                            {% for account in accounts %}
                                <li><a class="dropdown-item" href="{% url 'core:set_main' id=account.id %}">{{account.name}}</a></li>
                            {% endfor %}
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="{% url 'core:list' %}">Manage Accounts</a></li>
                        </ul>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:create' %}">Create Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:set_leverage' %}">Set Leverage</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:set_cross_margin' %}">Set Cross Margin</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock content %}
    {% block scripts %}
    {% endblock scripts %}
</body>
</html>

templates/core/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Create a Binance Futures Account
{% endblock title %}

{% block content %}
  <div class="container text-center mt-5">
    <div class="row">
        {% if messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            You should check in on the errors below.
            <ul>
              {% for message in messages %}
                <li>{{ message }}</li>
              {% endfor %}
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endif %}
        <div class="col-md-6 offset-md-3 card">
            <div class="card-body">
              <form method="POST" id="form-body">
                {% csrf_token %}
                <h5 class="card-title">Create an account</h5>
                <div class="mb-3">
                    <label class="form-label">Name your account</label>
                    <input type="text" class="form-control" name="name" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">Secret Key</label>
                    <input type="text" class="form-control" name="secret_key" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">API Key</label>
                    <input type="text" class="form-control" name="api_key" required>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
              </form>
            </div>
        </div>
    </div>
    
  </div>
  
{% endblock content %}

templates/core/delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Delete Account : {{account.name}}
{% endblock title %}

{% block content %}
  <div class="container text-center mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3 card">
            <div class="card-body">
              <form method="POST" id="form-body">
                {% csrf_token %}
                <h5 class="card-title mb-3">Are you sure you want to delete account "{{account.name}}"?</h5>
                <a href="{% url 'core:list' %}" class="btn btn-dark">Take me back</a>
                <input type="submit" class="btn btn-danger" value="Confirm">
              </form>
            </div>
        </div>
    </div>
  </div>
{% endblock content %}

templates/core/index.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Binance Madnews Dashboard
{% endblock title %}

{% block content %}

{% if selected_account %}
<div class="text-center m-2">
  <div class="row">
    <div class="col-md-4 post-toasts-col"></div>
    <div class="col-md-4">
      {% if messages %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        <ul>
          {% for message in messages %}
            <li>{{ message }}</li>
          {% endfor %}
        </ul>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endif %}
      <div class="card">
        <div class="card-header">
          Account : {{selected_account.name}}
        </div>
        <div class="card-body">
          <form method="POST" id="form-body">
            {% csrf_token %}
            <div class="mb-3">
                <label class="form-label">Pair</label>
                <select class="form-select" name="pair" required>
                    <option disabled selected value> -- select an option -- </option>
                    {% for pair in selected_account.pairs.all %}
                      <option value="{{pair.name}}">{{pair.name}}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mb-3">
              <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="multiplier" value="0.25">
                  <label class="form-check-label" for="inlineRadio2">x0.25</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="multiplier" value="0.5" checked>
                  <label class="form-check-label" for="inlineRadio2">x0.5</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="multiplier" value="1">
                  <label class="form-check-label" for="inlineRadio2">x1</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="multiplier" value="1.5">
                  <label class="form-check-label" for="inlineRadio2">x1.5</label>
                </div>
                <div class="form-check form-check-inline">
                  <input class="form-check-input" type="radio" name="multiplier" value="2">
                  <label class="form-check-label" for="inlineRadio2">x2</label>
                </div>
            </div>
            <button type="submit" name="buy" class="btn btn-success">BUY</button>
            <button type="submit" name="sell" class="btn btn-danger">SELL</button>
          </form>
        </div>
      </div>
      <div class="card mt-2">
        <div class="card-header">
          Notifications
        </div>
        <div class="card-body">
          <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="checkbox" role="switch" id="postSound" checked>
            <label class="form-check-label">Post Notifications</label>
          </div>
          <div class="form-check form-switch form-check-inline">
            <input class="form-check-input" type="checkbox" role="switch" id="tweetSound" checked>
            <label class="form-check-label">Tweet Notifications</label>
          </div>
          <div class="form-check mt-2">
            <button type="button" id="clearNotifications" class="btn btn-dark">clear</button>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 mt-2">
          <div class="card text-center">
            <div class="card-header">
              Balance
            </div>
            <div class="card-body">
              <p class="card-text">{{selected_account.balance}} USDT</p>
              <a href="{% url 'core:update_balance' %}" class="btn btn-primary btn-sm">Update</a>
            </div>
          </div>
        </div>
        <div class="col-md-6 mt-2">
          <div class="card text-center">
            <div class="card-header">
              Pairs
            </div>
            <div class="card-body">
              <p class="card-text">{{selected_account.pairs.count}} Pairs</p>
              <a href="{% url 'core:get_pairs' %}" class="btn btn-primary btn-sm">Update</a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4 tweet-toasts-col">
    </div>
  </div>
</div>
{% else %}
<div class="container text-center mt-5">
  <div class="row">
    <div class="col-md-4 offset-md-4 card">
      <div class="card-body">
        <h5 class="card-title">No Accounts Selected</h5>
        <p class="card-text">Create and setup an account to start trading</p>
        <p class="card-text">Or select an existing account from the Accounts section below on the navbar</p>
        <a href="{% url 'core:create' %}" class="btn btn-primary">Create Account</a>
      </div>
    </div>
  </div>
</div>
{% endif %}
  
{% endblock content %}

{% block scripts %}
<script src="{% static 'js/toasts.js' %}"></script>
<script src="{% static 'js/websocket.js' %}"></script>
{% endblock scripts %}

templates/core/list.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Accounts
{% endblock title %}

{% block content %}
  <div class="container text-center mt-5">
    <div class="row">
        <div class="card">
            <div class="card-body">
                <table class="table">
                    <thead class="table-secondary">
                        <tr>
                            <th scope="col">Account Name</th>
                            <th scope="col">API Key</th>
                            <th scope="col">Secret Key</th>
                            <th scope="col">Created Date</th>
                            <th scope="col">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for account in object_list %}
                        <tr>
                            <td>{{account.name}}</td>
                            <td>{{account.api_key|truncatechars:8}}</td>
                            <td>{{account.secret_key|truncatechars:8}}</td>
                            <td>{{account.created_date|date:"D d M Y"}}</td>
                            <td>
                                <a href="{% url 'core:update' id=account.id %}" class="btn btn-secondary">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                        <path d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"></path>
                                    </svg>
                                </a>
                                <a href="{% url 'core:delete' id=account.id %}" class="btn btn-secondary">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash2-fill" viewBox="0 0 16 16">
                                        <path d="M2.037 3.225A.703.703 0 0 1 2 3c0-1.105 2.686-2 6-2s6 .895 6 2a.702.702 0 0 1-.037.225l-1.684 10.104A2 2 0 0 1 10.305 15H5.694a2 2 0 0 1-1.973-1.671L2.037 3.225zm9.89-.69C10.966 2.214 9.578 2 8 2c-1.58 0-2.968.215-3.926.534-.477.16-.795.327-.975.466.18.14.498.307.975.466C5.032 3.786 6.42 4 8 4s2.967-.215 3.926-.534c.477-.16.795-.327.975-.466-.18-.14-.498-.307-.975-.466z"></path>
                                    </svg>
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    
  </div>
  
{% endblock content %}

templates/core/update.html
{% extends "base.html" %}
{% load static %}

{% block title %}
  Update Account {{account.name}}
{% endblock title %}

{% block content %}
  <div class="container text-center mt-5">
    <div class="row">
        {% if messages %}
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            You should check in on the errors below.
            <ul>
              {% for message in messages %}
                <li>{{ message }}</li>
              {% endfor %}
            </ul>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>
        {% endif %}
        <div class="col-md-6 offset-md-3 card">
            <div class="card-body">
              <form method="POST" id="form-body">
                {% csrf_token %}
                <h5 class="card-title">Update account {{account.name}}</h5>
                <div class="mb-3">
                    <label class="form-label">Name</label>
                    <input type="text" class="form-control" name="name" value="{{account.name}}" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">Secret Key</label>
                    <input type="text" class="form-control" name="secret_key" value="{{account.secret_key}}" required>
                </div>
                <div class="mb-3">
                    <label class="form-label">API Key</label>
                    <input type="text" class="form-control" name="api_key" value="{{account.api_key}}" required>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
              </form>
            </div>
        </div>
    </div>
    
  </div>
  
{% endblock content %}